databases:
  - name: ASOBOUNO_db
    databaseName: asobouno_db_g1m0
    user: ASOBOUNO
    region: singapore

services:
  - type: web
    name: ASOBOUNO
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ASOBOUNO_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

